### ISSUE TITLE
Render/Visualize HPS results

### ISSUE THREAD

**Issue by umariqb** [aymenmir1/hps#1]
Hi Vladimir and Aymen,

Great work! Can you please help in visualizing/rendering the final HPS results e.g., as shown here in your video:

https://youtu.be/ByPSN_yVK_I?t=146

Thanks,
Umar

**Comment by vguzov** [comment]
Hello Umar,
Thank you very much! The visualization software is currently being prepared for release and will be released a bit later

Best,
Vladimir

**Comment by umariqb** [comment]
Hi Vladimir,

Any ETA? 

Best,
Umar

**Comment by vguzov** [comment]
Hi Umar,
Hopefully in about a month or so it should be there! We can post a message here once it will be published

**Comment by vguzov** [comment]
Hi again,
The code for visualization that we used in our videos is now available as a python package!
Here is the link: https://github.com/vguzov/cloudrender
It also features a sample script (test_scene_video.py) that explains how to render pointclouds, dynamic motion and shadows. Hope that helps!

Best,
Vladimir

**Comment by umariqb** [comment]
Hi Vladimir,

That's great. Thanks a lot for letting me know. 

You can close the issue now. 

Best,
Umar
