### ISSUE TITLE
MVNX files and untangle library

### ISSUE THREAD

**Issue by yufu-liu** [aymenmir1/hps#3]
Hi, thanks for providing this amazing dataset!

I encountered an issue when running **preprocess.py**. The error shows below, and I guess it was caused by the content in MVNX files. 
BTW, I also suspect my environment could lead the issue. (My current OS is Windows, and IDE is PyCharm and Python 3.10.)

> Traceback (most recent call last):
>   File "C:\Users\Ryan_liu\AppData\Local\Programs\Python\Python310\lib\xml\sax\ex
> patreader.py", line 217, in feed
>     self._parser.Parse(data, isFinal)
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2 

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Ryan_liu\platform-tools_r34.0.0-windows\platform-tools\hps-main
> \preprocess\preprocess.py", line 179, in <module>
>     data = mvnx.MVNX(mvnx_name)
>   File "C:\Users\Ryan_liu\platform-tools_r34.0.0-windows\platform-tools\hps-main
> \preprocess\xsens\mvnx.py", line 202, in __init__
>     self.xml_file=untangle.parse(mvnx_root)
>   File "C:\Users\Ryan_liu\AppData\Local\Programs\Python\Python310\lib\site-packa
> ges\untangle.py", line 211, in parse
>     parser.parse(StringIO(filename))
>   File "C:\Users\Ryan_liu\AppData\Local\Programs\Python\Python310\lib\xml\sax\ex
> patreader.py", line 111, in parse
>     xmlreader.IncrementalParser.parse(self, source)
>   File "C:\Users\Ryan_liu\AppData\Local\Programs\Python\Python310\lib\xml\sax\xm
> lreader.py", line 125, in parse
>     self.feed(buffer)
>   File "C:\Users\Ryan_liu\AppData\Local\Programs\Python\Python310\lib\xml\sax\ex
> patreader.py", line 221, in feed
>     self._err_handler.fatalError(exc)
>   File "C:\Users\Ryan_liu\AppData\Local\Programs\Python\Python310\lib\xml\sax\ha
> ndler.py", line 38, in fatalError
> 

Hope someone could give me some advices or solutions.

**Comment by vguzov** [comment]
Hi, I think I saw this error before, it's in the .mvnx reader, and if I remember correctly, this may happen if the filepath you supply doesn't exist (in that case double-check that you set all the paths in `global_vars.py`), or that the path is not a `str` object, e.g. if you changed the code and converted it to `pathlib.Path` (in that case convert in back to str). This may be also caused by some Windows-specific behaviour (we only tested on Ubuntu), but it's less probable.

**Comment by yufu-liu** [comment]
Hi, I have solved it now. Thanks for your answering!

By the way, Do you know how to align the coordinate system of Xsens with right-hand system which is used by AMASS in SMPL format?
First, I mapped Xsens to SMPL by similar joints. (Remove L5 joint)
Second, I know each IMU of Xsens records the data independently, so all of them need to align to pelvis joint's coordinate system. 
Then I observed the mesh of AMASS by the same view angle, and rotated T-pose data in the Xsens data to the same as the one in AMASS.
However, when the mesh moves from T-pose, the limbs seemed to be uncoordinated. 

Hope someone could give me some advices!

**Comment by HandiYin** [comment]
> Hi, I have solved it now. Thanks for your answering!
> 
> By the way, Do you know how to align the coordinate system of Xsens with right-hand system which is used by AMASS in SMPL format? First, I mapped Xsens to SMPL by similar joints. (Remove L5 joint) Second, I know each IMU of Xsens records the data independently, so all of them need to align to pelvis joint's coordinate system. Then I observed the mesh of AMASS by the same view angle, and rotated T-pose data in the Xsens data to the same as the one in AMASS. However, when the mesh moves from T-pose, the limbs seemed to be uncoordinated.
> 
> Hope someone could give me some advices!

Hi! Do u know how to convert now? I'm meeting the same problem
